// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/widgets/homeserver_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:kohera/core/models/server_auth_capabilities.dart' as _i9;
import 'package:kohera/core/services/matrix_service.dart' as _i10;
import 'package:kohera/core/services/sub_services/auth_service.dart' as _i8;
import 'package:kohera/core/services/sub_services/chat_backup_service.dart'
    as _i5;
import 'package:kohera/core/services/sub_services/selection_service.dart'
    as _i6;
import 'package:kohera/core/services/sub_services/sync_service.dart' as _i7;
import 'package:kohera/core/services/sub_services/uia_service.dart' as _i4;
import 'package:kohera/features/notifications/services/call_push_rule_manager.dart'
    as _i2;
import 'package:matrix/matrix.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCallPushRuleManager_0 extends _i1.SmartFake
    implements _i2.CallPushRuleManager {
  _FakeCallPushRuleManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUiaService_2 extends _i1.SmartFake implements _i4.UiaService {
  _FakeUiaService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatBackupService_3 extends _i1.SmartFake
    implements _i5.ChatBackupService {
  _FakeChatBackupService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectionService_4 extends _i1.SmartFake
    implements _i6.SelectionService {
  _FakeSelectionService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncService_5 extends _i1.SmartFake implements _i7.SyncService {
  _FakeSyncService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthService_6 extends _i1.SmartFake implements _i8.AuthService {
  _FakeAuthService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerAuthCapabilities_7 extends _i1.SmartFake
    implements _i9.ServerAuthCapabilities {
  _FakeServerAuthCapabilities_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatrixService extends _i1.Mock implements _i10.MatrixService {
  @override
  _i2.CallPushRuleManager get callPushRuleManager => (super.noSuchMethod(
        Invocation.getter(#callPushRuleManager),
        returnValue: _FakeCallPushRuleManager_0(
          this,
          Invocation.getter(#callPushRuleManager),
        ),
        returnValueForMissingStub: _FakeCallPushRuleManager_0(
          this,
          Invocation.getter(#callPushRuleManager),
        ),
      ) as _i2.CallPushRuleManager);

  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  _i3.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.Client);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.UiaService get uia => (super.noSuchMethod(
        Invocation.getter(#uia),
        returnValue: _FakeUiaService_2(
          this,
          Invocation.getter(#uia),
        ),
        returnValueForMissingStub: _FakeUiaService_2(
          this,
          Invocation.getter(#uia),
        ),
      ) as _i4.UiaService);

  @override
  _i5.ChatBackupService get chatBackup => (super.noSuchMethod(
        Invocation.getter(#chatBackup),
        returnValue: _FakeChatBackupService_3(
          this,
          Invocation.getter(#chatBackup),
        ),
        returnValueForMissingStub: _FakeChatBackupService_3(
          this,
          Invocation.getter(#chatBackup),
        ),
      ) as _i5.ChatBackupService);

  @override
  _i6.SelectionService get selection => (super.noSuchMethod(
        Invocation.getter(#selection),
        returnValue: _FakeSelectionService_4(
          this,
          Invocation.getter(#selection),
        ),
        returnValueForMissingStub: _FakeSelectionService_4(
          this,
          Invocation.getter(#selection),
        ),
      ) as _i6.SelectionService);

  @override
  _i7.SyncService get sync => (super.noSuchMethod(
        Invocation.getter(#sync),
        returnValue: _FakeSyncService_5(
          this,
          Invocation.getter(#sync),
        ),
        returnValueForMissingStub: _FakeSyncService_5(
          this,
          Invocation.getter(#sync),
        ),
      ) as _i7.SyncService);

  @override
  _i8.AuthService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuthService_6(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeAuthService_6(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i8.AuthService);

  @override
  bool get hasSkippedSetup => (super.noSuchMethod(
        Invocation.getter(#hasSkippedSetup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set callPushRuleManager(_i2.CallPushRuleManager? value) => super.noSuchMethod(
        Invocation.setter(
          #callPushRuleManager,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoggedInForTest(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedInForTest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set uia(_i4.UiaService? value) => super.noSuchMethod(
        Invocation.setter(
          #uia,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set chatBackup(_i5.ChatBackupService? value) => super.noSuchMethod(
        Invocation.setter(
          #chatBackup,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selection(_i6.SelectionService? value) => super.noSuchMethod(
        Invocation.setter(
          #selection,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sync(_i7.SyncService? value) => super.noSuchMethod(
        Invocation.setter(
          #sync,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set auth(_i8.AuthService? value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skipSetup() => super.noSuchMethod(
        Invocation.method(
          #skipSetup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> init({bool? restoreSession = true}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#restoreSession: restoreSession},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i12.Future<bool>.value(false),
        returnValueForMissingStub: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i12.Future<bool>.value(false),
        returnValueForMissingStub: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<void> completeRegistration(
    _i3.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> handleSoftLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleSoftLogout,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoggedIn(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedIn,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loginError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #loginError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i12.Future<bool>.value(false),
        returnValueForMissingStub: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i12.Future<bool>.value(false),
        returnValueForMissingStub: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<void> completeRegistration(
    _i3.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void activateRestoredSession() => super.noSuchMethod(
        Invocation.method(
          #activateRestoredSession,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> handleServerLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleServerLogout,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveSessionBackup() => (super.noSuchMethod(
        Invocation.method(
          #saveSessionBackup,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i9.ServerAuthCapabilities> getServerAuthCapabilities(
    String? homeserver, {
    required bool? isLoggedIn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerAuthCapabilities,
          [homeserver],
          {#isLoggedIn: isLoggedIn},
        ),
        returnValue: _i12.Future<_i9.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_7(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
            {#isLoggedIn: isLoggedIn},
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i9.ServerAuthCapabilities>.value(
                _FakeServerAuthCapabilities_7(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
            {#isLoggedIn: isLoggedIn},
          ),
        )),
      ) as _i12.Future<_i9.ServerAuthCapabilities>);

  @override
  bool isPermanentAuthFailure(Object? error) => (super.noSuchMethod(
        Invocation.method(
          #isPermanentAuthFailure,
          [error],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i12.Future<void> clearSessionKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionKeys,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> migrateStorageKeys() => (super.noSuchMethod(
        Invocation.method(
          #migrateStorageKeys,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> persistCredentials() => (super.noSuchMethod(
        Invocation.method(
          #persistCredentials,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
