// Mocks generated by Mockito 5.4.6 from annotations
// in lattice/test/widgets/homeserver_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:lattice/core/models/server_auth_capabilities.dart' as _i3;
import 'package:lattice/core/models/space_node.dart' as _i7;
import 'package:lattice/core/services/matrix_service.dart' as _i4;
import 'package:matrix/matrix.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerAuthCapabilities_1 extends _i1.SmartFake
    implements _i3.ServerAuthCapabilities {
  _FakeServerAuthCapabilities_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatrixService extends _i1.Mock implements _i4.MatrixService {
  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Stream<_i2.UiaRequest<dynamic>> get onUiaRequest => (super.noSuchMethod(
        Invocation.getter(#onUiaRequest),
        returnValue: _i6.Stream<_i2.UiaRequest<dynamic>>.empty(),
        returnValueForMissingStub: _i6.Stream<_i2.UiaRequest<dynamic>>.empty(),
      ) as _i6.Stream<_i2.UiaRequest<dynamic>>);

  @override
  bool get chatBackupEnabled => (super.noSuchMethod(
        Invocation.getter(#chatBackupEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get chatBackupLoading => (super.noSuchMethod(
        Invocation.getter(#chatBackupLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSkippedSetup => (super.noSuchMethod(
        Invocation.getter(#hasSkippedSetup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Set<String> get selectedSpaceIds => (super.noSuchMethod(
        Invocation.getter(#selectedSpaceIds),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  List<_i7.SpaceNode> get spaceTree => (super.noSuchMethod(
        Invocation.getter(#spaceTree),
        returnValue: <_i7.SpaceNode>[],
        returnValueForMissingStub: <_i7.SpaceNode>[],
      ) as List<_i7.SpaceNode>);

  @override
  List<_i2.Room> get spaces => (super.noSuchMethod(
        Invocation.getter(#spaces),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  List<_i2.Room> get topLevelSpaces => (super.noSuchMethod(
        Invocation.getter(#topLevelSpaces),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  List<_i2.Room> get rooms => (super.noSuchMethod(
        Invocation.getter(#rooms),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  List<_i2.Room> get invitedRooms => (super.noSuchMethod(
        Invocation.getter(#invitedRooms),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  List<_i2.Room> get invitedSpaces => (super.noSuchMethod(
        Invocation.getter(#invitedSpaces),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  List<_i2.Room> get orphanRooms => (super.noSuchMethod(
        Invocation.getter(#orphanRooms),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  bool get syncing => (super.noSuchMethod(
        Invocation.getter(#syncing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoggedInForTest(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedInForTest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void completeUiaWithPassword(
    _i2.UiaRequest<dynamic>? request,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #completeUiaWithPassword,
          [
            request,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCachedPassword() => super.noSuchMethod(
        Invocation.method(
          #clearCachedPassword,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> checkChatBackupStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkChatBackupStatus,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void requestMissingRoomKeys() => super.noSuchMethod(
        Invocation.method(
          #requestMissingRoomKeys,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<String?> getStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredRecoveryKey,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> storeRecoveryKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeRecoveryKey,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteStoredRecoveryKey,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> disableChatBackup() => (super.noSuchMethod(
        Invocation.method(
          #disableChatBackup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> tryAutoUnlockBackup() => (super.noSuchMethod(
        Invocation.method(
          #tryAutoUnlockBackup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void skipSetup() => super.noSuchMethod(
        Invocation.method(
          #skipSetup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectSpace(String? spaceId) => super.noSuchMethod(
        Invocation.method(
          #selectSpace,
          [spaceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleSpaceSelection(String? spaceId) => super.noSuchMethod(
        Invocation.method(
          #toggleSpaceSelection,
          [spaceId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSpaceSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSpaceSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectRoom(String? roomId) => super.noSuchMethod(
        Invocation.method(
          #selectRoom,
          [roomId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSpaceOrder(List<String>? order) => super.noSuchMethod(
        Invocation.method(
          #updateSpaceOrder,
          [order],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? inviterDisplayName(_i2.Room? room) => (super.noSuchMethod(
        Invocation.method(
          #inviterDisplayName,
          [room],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  List<_i2.Room> roomsForSpace(String? spaceId) => (super.noSuchMethod(
        Invocation.method(
          #roomsForSpace,
          [spaceId],
        ),
        returnValue: <_i2.Room>[],
        returnValueForMissingStub: <_i2.Room>[],
      ) as List<_i2.Room>);

  @override
  Set<String> spaceMemberships(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #spaceMemberships,
          [roomId],
        ),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  int unreadCountForSpace(String? spaceId) => (super.noSuchMethod(
        Invocation.method(
          #unreadCountForSpace,
          [spaceId],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void invalidateSpaceTree() => super.noSuchMethod(
        Invocation.method(
          #invalidateSpaceTree,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i3.ServerAuthCapabilities> getServerAuthCapabilities(
          String? homeserver) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerAuthCapabilities,
          [homeserver],
        ),
        returnValue: _i6.Future<_i3.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_1(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i3.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_1(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
          ),
        )),
      ) as _i6.Future<_i3.ServerAuthCapabilities>);

  @override
  _i6.Future<void> init({bool? restoreSession = true}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#restoreSession: restoreSession},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveSessionBackup() => (super.noSuchMethod(
        Invocation.method(
          #saveSessionBackup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> completeRegistration(
    _i2.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> handleSoftLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleSoftLogout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}
