// Mocks generated by Mockito 5.4.6 from annotations
// in lattice/test/widgets/key_backup_banner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:lattice/core/models/server_auth_capabilities.dart' as _i4;
import 'package:lattice/core/services/matrix_service.dart' as _i5;
import 'package:lattice/core/services/sub_services/selection_service.dart'
    as _i3;
import 'package:matrix/matrix.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectionService_1 extends _i1.SmartFake
    implements _i3.SelectionService {
  _FakeSelectionService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerAuthCapabilities_2 extends _i1.SmartFake
    implements _i4.ServerAuthCapabilities {
  _FakeServerAuthCapabilities_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatrixService extends _i1.Mock implements _i5.MatrixService {
  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.SelectionService get selection => (super.noSuchMethod(
        Invocation.getter(#selection),
        returnValue: _FakeSelectionService_1(
          this,
          Invocation.getter(#selection),
        ),
        returnValueForMissingStub: _FakeSelectionService_1(
          this,
          Invocation.getter(#selection),
        ),
      ) as _i3.SelectionService);

  @override
  _i7.Stream<_i2.UiaRequest<dynamic>> get onUiaRequest => (super.noSuchMethod(
        Invocation.getter(#onUiaRequest),
        returnValue: _i7.Stream<_i2.UiaRequest<dynamic>>.empty(),
        returnValueForMissingStub: _i7.Stream<_i2.UiaRequest<dynamic>>.empty(),
      ) as _i7.Stream<_i2.UiaRequest<dynamic>>);

  @override
  bool get chatBackupEnabled => (super.noSuchMethod(
        Invocation.getter(#chatBackupEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get chatBackupLoading => (super.noSuchMethod(
        Invocation.getter(#chatBackupLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSkippedSetup => (super.noSuchMethod(
        Invocation.getter(#hasSkippedSetup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get syncing => (super.noSuchMethod(
        Invocation.getter(#syncing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoggedInForTest(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedInForTest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selection(_i3.SelectionService? value) => super.noSuchMethod(
        Invocation.setter(
          #selection,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void completeUiaWithPassword(
    _i2.UiaRequest<dynamic>? request,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #completeUiaWithPassword,
          [
            request,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCachedPassword() => super.noSuchMethod(
        Invocation.method(
          #clearCachedPassword,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> checkChatBackupStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkChatBackupStatus,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void requestMissingRoomKeys() => super.noSuchMethod(
        Invocation.method(
          #requestMissingRoomKeys,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String?> getStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredRecoveryKey,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
        returnValueForMissingStub: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> storeRecoveryKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeRecoveryKey,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteStoredRecoveryKey,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> disableChatBackup() => (super.noSuchMethod(
        Invocation.method(
          #disableChatBackup,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> tryAutoUnlockBackup() => (super.noSuchMethod(
        Invocation.method(
          #tryAutoUnlockBackup,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void skipSetup() => super.noSuchMethod(
        Invocation.method(
          #skipSetup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.ServerAuthCapabilities> getServerAuthCapabilities(
          String? homeserver) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerAuthCapabilities,
          [homeserver],
        ),
        returnValue: _i7.Future<_i4.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_2(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_2(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
          ),
        )),
      ) as _i7.Future<_i4.ServerAuthCapabilities>);

  @override
  _i7.Future<void> init({bool? restoreSession = true}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#restoreSession: restoreSession},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveSessionBackup() => (super.noSuchMethod(
        Invocation.method(
          #saveSessionBackup,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> completeRegistration(
    _i2.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> handleSoftLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleSoftLogout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}
