// Mocks generated by Mockito 5.4.6 from annotations
// in lattice/test/widgets/key_backup_banner_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:lattice/core/services/sub_services/chat_backup_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatBackupService extends _i1.Mock implements _i2.ChatBackupService {
  @override
  bool get chatBackupEnabled => (super.noSuchMethod(
        Invocation.getter(#chatBackupEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get chatBackupLoading => (super.noSuchMethod(
        Invocation.getter(#chatBackupLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> checkChatBackupStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkChatBackupStatus,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disableChatBackup() => (super.noSuchMethod(
        Invocation.method(
          #disableChatBackup,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void resetChatBackupState() => super.noSuchMethod(
        Invocation.method(
          #resetChatBackupState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> tryAutoUnlockBackup() => (super.noSuchMethod(
        Invocation.method(
          #tryAutoUnlockBackup,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void requestMissingRoomKeys() => super.noSuchMethod(
        Invocation.method(
          #requestMissingRoomKeys,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String?> getStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #getStoredRecoveryKey,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> storeRecoveryKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #storeRecoveryKey,
          [key],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStoredRecoveryKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteStoredRecoveryKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
