// Mocks generated by Mockito 5.4.6 from annotations
// in lattice/test/services/chat_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:matrix/matrix.dart' as _i2;
import 'package:matrix/src/models/timeline_chunk.dart' as _i7;
import 'package:matrix/src/utils/cached_stream_controller.dart' as _i3;
import 'package:matrix/src/utils/space_child.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoomSummary_0 extends _i1.SmartFake implements _i2.RoomSummary {
  _FakeRoomSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachedStreamController_1<T> extends _i1.SmartFake
    implements _i3.CachedStreamController<T> {
  _FakeCachedStreamController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_2 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLatestReceiptState_4 extends _i1.SmartFake
    implements _i2.LatestReceiptState {
  _FakeLatestReceiptState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncUpdate_5 extends _i1.SmartFake implements _i2.SyncUpdate {
  _FakeSyncUpdate_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeline_6 extends _i1.SmartFake implements _i2.Timeline {
  _FakeTimeline_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_7 extends _i1.SmartFake implements _i2.User {
  _FakeUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_8 extends _i1.SmartFake implements Uri {
  _FakeUri_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoom_9 extends _i1.SmartFake implements _i2.Room {
  _FakeRoom_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatrixFile_10 extends _i1.SmartFake implements _i2.MatrixFile {
  _FakeMatrixFile_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_11 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Room].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoom extends _i1.Mock implements _i2.Room {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.Membership get membership => (super.noSuchMethod(
        Invocation.getter(#membership),
        returnValue: _i2.Membership.ban,
        returnValueForMissingStub: _i2.Membership.ban,
      ) as _i2.Membership);

  @override
  int get notificationCount => (super.noSuchMethod(
        Invocation.getter(#notificationCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get highlightCount => (super.noSuchMethod(
        Invocation.getter(#highlightCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i2.RoomSummary get summary => (super.noSuchMethod(
        Invocation.getter(#summary),
        returnValue: _FakeRoomSummary_0(
          this,
          Invocation.getter(#summary),
        ),
        returnValueForMissingStub: _FakeRoomSummary_0(
          this,
          Invocation.getter(#summary),
        ),
      ) as _i2.RoomSummary);

  @override
  Map<String, Map<String, _i2.StrippedStateEvent>> get states =>
      (super.noSuchMethod(
        Invocation.getter(#states),
        returnValue: <String, Map<String, _i2.StrippedStateEvent>>{},
        returnValueForMissingStub: <String,
            Map<String, _i2.StrippedStateEvent>>{},
      ) as Map<String, Map<String, _i2.StrippedStateEvent>>);

  @override
  Map<String, _i2.BasicEvent> get ephemerals => (super.noSuchMethod(
        Invocation.getter(#ephemerals),
        returnValue: <String, _i2.BasicEvent>{},
        returnValueForMissingStub: <String, _i2.BasicEvent>{},
      ) as Map<String, _i2.BasicEvent>);

  @override
  Map<String, _i2.BasicEvent> get roomAccountData => (super.noSuchMethod(
        Invocation.getter(#roomAccountData),
        returnValue: <String, _i2.BasicEvent>{},
        returnValueForMissingStub: <String, _i2.BasicEvent>{},
      ) as Map<String, _i2.BasicEvent>);

  @override
  List<_i5.Completer<dynamic>> get sendingQueue => (super.noSuchMethod(
        Invocation.getter(#sendingQueue),
        returnValue: <_i5.Completer<dynamic>>[],
        returnValueForMissingStub: <_i5.Completer<dynamic>>[],
      ) as List<_i5.Completer<dynamic>>);

  @override
  List<String> get sendingQueueEventsByTxId => (super.noSuchMethod(
        Invocation.getter(#sendingQueueEventsByTxId),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  bool get partial => (super.noSuchMethod(
        Invocation.getter(#partial),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get fullyRead => (super.noSuchMethod(
        Invocation.getter(#fullyRead),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#fullyRead),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#fullyRead),
        ),
      ) as String);

  @override
  _i3.CachedStreamController<String> get onUpdate => (super.noSuchMethod(
        Invocation.getter(#onUpdate),
        returnValue: _FakeCachedStreamController_1<String>(
          this,
          Invocation.getter(#onUpdate),
        ),
        returnValueForMissingStub: _FakeCachedStreamController_1<String>(
          this,
          Invocation.getter(#onUpdate),
        ),
      ) as _i3.CachedStreamController<String>);

  @override
  _i3.CachedStreamController<String> get onSessionKeyReceived =>
      (super.noSuchMethod(
        Invocation.getter(#onSessionKeyReceived),
        returnValue: _FakeCachedStreamController_1<String>(
          this,
          Invocation.getter(#onSessionKeyReceived),
        ),
        returnValueForMissingStub: _FakeCachedStreamController_1<String>(
          this,
          Invocation.getter(#onSessionKeyReceived),
        ),
      ) as _i3.CachedStreamController<String>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<String> get pinnedEventIds => (super.noSuchMethod(
        Invocation.getter(#pinnedEventIds),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  String get topic => (super.noSuchMethod(
        Invocation.getter(#topic),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#topic),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#topic),
        ),
      ) as String);

  @override
  String get canonicalAlias => (super.noSuchMethod(
        Invocation.getter(#canonicalAlias),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#canonicalAlias),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#canonicalAlias),
        ),
      ) as String);

  @override
  bool get isDirectChat => (super.noSuchMethod(
        Invocation.getter(#isDirectChat),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i2.User> get typingUsers => (super.noSuchMethod(
        Invocation.getter(#typingUsers),
        returnValue: <_i2.User>[],
        returnValueForMissingStub: <_i2.User>[],
      ) as List<_i2.User>);

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_2(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_2(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  bool get isAbandonedDMRoom => (super.noSuchMethod(
        Invocation.getter(#isAbandonedDMRoom),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get displayname => (super.noSuchMethod(
        Invocation.getter(#displayname),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#displayname),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#displayname),
        ),
      ) as String);

  @override
  DateTime get latestEventReceivedTime => (super.noSuchMethod(
        Invocation.getter(#latestEventReceivedTime),
        returnValue: _FakeDateTime_3(
          this,
          Invocation.getter(#latestEventReceivedTime),
        ),
        returnValueForMissingStub: _FakeDateTime_3(
          this,
          Invocation.getter(#latestEventReceivedTime),
        ),
      ) as DateTime);

  @override
  Map<String, _i2.Tag> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <String, _i2.Tag>{},
        returnValueForMissingStub: <String, _i2.Tag>{},
      ) as Map<String, _i2.Tag>);

  @override
  bool get markedUnread => (super.noSuchMethod(
        Invocation.getter(#markedUnread),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasNewMessages => (super.noSuchMethod(
        Invocation.getter(#hasNewMessages),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.LatestReceiptState get receiptState => (super.noSuchMethod(
        Invocation.getter(#receiptState),
        returnValue: _FakeLatestReceiptState_4(
          this,
          Invocation.getter(#receiptState),
        ),
        returnValueForMissingStub: _FakeLatestReceiptState_4(
          this,
          Invocation.getter(#receiptState),
        ),
      ) as _i2.LatestReceiptState);

  @override
  bool get isUnread => (super.noSuchMethod(
        Invocation.getter(#isUnread),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isUnreadOrInvited => (super.noSuchMethod(
        Invocation.getter(#isUnreadOrInvited),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<_i2.SyncUpdate> get waitForSync => (super.noSuchMethod(
        Invocation.getter(#waitForSync),
        returnValue: _i5.Future<_i2.SyncUpdate>.value(_FakeSyncUpdate_5(
          this,
          Invocation.getter(#waitForSync),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.SyncUpdate>.value(_FakeSyncUpdate_5(
          this,
          Invocation.getter(#waitForSync),
        )),
      ) as _i5.Future<_i2.SyncUpdate>);

  @override
  bool get isFavourite => (super.noSuchMethod(
        Invocation.getter(#isFavourite),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, _i2.MatrixFile> get sendingFilePlaceholders =>
      (super.noSuchMethod(
        Invocation.getter(#sendingFilePlaceholders),
        returnValue: <String, _i2.MatrixFile>{},
        returnValueForMissingStub: <String, _i2.MatrixFile>{},
      ) as Map<String, _i2.MatrixFile>);

  @override
  Map<String, _i2.MatrixImageFile> get sendingFileThumbnails =>
      (super.noSuchMethod(
        Invocation.getter(#sendingFileThumbnails),
        returnValue: <String, _i2.MatrixImageFile>{},
        returnValueForMissingStub: <String, _i2.MatrixImageFile>{},
      ) as Map<String, _i2.MatrixImageFile>);

  @override
  bool get isFederated => (super.noSuchMethod(
        Invocation.getter(#isFederated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isArchived => (super.noSuchMethod(
        Invocation.getter(#isArchived),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get participantListComplete => (super.noSuchMethod(
        Invocation.getter(#participantListComplete),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Set<String> get creatorUserIds => (super.noSuchMethod(
        Invocation.getter(#creatorUserIds),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  int get ownPowerLevel => (super.noSuchMethod(
        Invocation.getter(#ownPowerLevel),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get canBan => (super.noSuchMethod(
        Invocation.getter(#canBan),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get groupCallsEnabledForEveryone => (super.noSuchMethod(
        Invocation.getter(#groupCallsEnabledForEveryone),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canJoinGroupCall => (super.noSuchMethod(
        Invocation.getter(#canJoinGroupCall),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canSendDefaultMessages => (super.noSuchMethod(
        Invocation.getter(#canSendDefaultMessages),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canInvite => (super.noSuchMethod(
        Invocation.getter(#canInvite),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canKick => (super.noSuchMethod(
        Invocation.getter(#canKick),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canRedact => (super.noSuchMethod(
        Invocation.getter(#canRedact),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canSendDefaultStates => (super.noSuchMethod(
        Invocation.getter(#canSendDefaultStates),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canChangePowerLevel => (super.noSuchMethod(
        Invocation.getter(#canChangePowerLevel),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.PushRuleState get pushRuleState => (super.noSuchMethod(
        Invocation.getter(#pushRuleState),
        returnValue: _i2.PushRuleState.notify,
        returnValueForMissingStub: _i2.PushRuleState.notify,
      ) as _i2.PushRuleState);

  @override
  bool get canChangeJoinRules => (super.noSuchMethod(
        Invocation.getter(#canChangeJoinRules),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.GuestAccess get guestAccess => (super.noSuchMethod(
        Invocation.getter(#guestAccess),
        returnValue: _i2.GuestAccess.canJoin,
        returnValueForMissingStub: _i2.GuestAccess.canJoin,
      ) as _i2.GuestAccess);

  @override
  bool get canChangeGuestAccess => (super.noSuchMethod(
        Invocation.getter(#canChangeGuestAccess),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get canChangeHistoryVisibility => (super.noSuchMethod(
        Invocation.getter(#canChangeHistoryVisibility),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get encrypted => (super.noSuchMethod(
        Invocation.getter(#encrypted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isExtinct => (super.noSuchMethod(
        Invocation.getter(#isExtinct),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSpace => (super.noSuchMethod(
        Invocation.getter(#isSpace),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i6.SpaceParent> get spaceParents => (super.noSuchMethod(
        Invocation.getter(#spaceParents),
        returnValue: <_i6.SpaceParent>[],
        returnValueForMissingStub: <_i6.SpaceParent>[],
      ) as List<_i6.SpaceParent>);

  @override
  List<_i6.SpaceChild> get spaceChildren => (super.noSuchMethod(
        Invocation.getter(#spaceChildren),
        returnValue: <_i6.SpaceChild>[],
        returnValueForMissingStub: <_i6.SpaceChild>[],
      ) as List<_i6.SpaceChild>);

  @override
  set membership(_i2.Membership? value) => super.noSuchMethod(
        Invocation.setter(
          #membership,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set notificationCount(int? value) => super.noSuchMethod(
        Invocation.setter(
          #notificationCount,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set highlightCount(int? value) => super.noSuchMethod(
        Invocation.setter(
          #highlightCount,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set prev_batch(String? value) => super.noSuchMethod(
        Invocation.setter(
          #prev_batch,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set summary(_i2.RoomSummary? value) => super.noSuchMethod(
        Invocation.setter(
          #summary,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set states(Map<String, Map<String, _i2.StrippedStateEvent>>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #states,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set ephemerals(Map<String, _i2.BasicEvent>? value) => super.noSuchMethod(
        Invocation.setter(
          #ephemerals,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set roomAccountData(Map<String, _i2.BasicEvent>? value) => super.noSuchMethod(
        Invocation.setter(
          #roomAccountData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set partial(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #partial,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastEvent(_i2.Event? value) => super.noSuchMethod(
        Invocation.setter(
          #lastEvent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set receiptState(_i2.LatestReceiptState? value) => super.noSuchMethod(
        Invocation.setter(
          #receiptState,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> postLoad() => (super.noSuchMethod(
        Invocation.method(
          #postLoad,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.StrippedStateEvent? getState(
    String? typeKey, [
    String? stateKey = '',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getState,
          [
            typeKey,
            stateKey,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i2.StrippedStateEvent?);

  @override
  void setState(_i2.StrippedStateEvent? state) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i2.User>> loadHeroUsers() => (super.noSuchMethod(
        Invocation.method(
          #loadHeroUsers,
          [],
        ),
        returnValue: _i5.Future<List<_i2.User>>.value(<_i2.User>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i5.Future<List<_i2.User>>);

  @override
  String getLocalizedDisplayname(
          [_i2.MatrixLocalizations? i18n =
              const _i2.MatrixDefaultLocalizations()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizedDisplayname,
          [i18n],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedDisplayname,
            [i18n],
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedDisplayname,
            [i18n],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> setCanonicalAlias(String? canonicalAlias) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanonicalAlias,
          [canonicalAlias],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Event?> refreshLastEvent(
          {Duration? timeout = const Duration(seconds: 30)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshLastEvent,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<_i2.Event?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Event?>.value(),
      ) as _i5.Future<_i2.Event?>);

  @override
  void setEphemeral(_i2.BasicEvent? ephemeral) => super.noSuchMethod(
        Invocation.method(
          #setEphemeral,
          [ephemeral],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<String> setName(String? newName) => (super.noSuchMethod(
        Invocation.method(
          #setName,
          [newName],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setName,
            [newName],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setName,
            [newName],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> setDescription(String? newName) => (super.noSuchMethod(
        Invocation.method(
          #setDescription,
          [newName],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setDescription,
            [newName],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setDescription,
            [newName],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> addTag(
    String? tag, {
    double? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [tag],
          {#order: order},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeTag(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #removeTag,
          [tag],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.SyncUpdate> waitForRoomInSync() => (super.noSuchMethod(
        Invocation.method(
          #waitForRoomInSync,
          [],
        ),
        returnValue: _i5.Future<_i2.SyncUpdate>.value(_FakeSyncUpdate_5(
          this,
          Invocation.method(
            #waitForRoomInSync,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.SyncUpdate>.value(_FakeSyncUpdate_5(
          this,
          Invocation.method(
            #waitForRoomInSync,
            [],
          ),
        )),
      ) as _i5.Future<_i2.SyncUpdate>);

  @override
  _i5.Future<void> markUnread(bool? unread) => (super.noSuchMethod(
        Invocation.method(
          #markUnread,
          [unread],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFavourite(bool? favourite) => (super.noSuchMethod(
        Invocation.method(
          #setFavourite,
          [favourite],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> setPinnedEvents(List<String>? pinnedEventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPinnedEvents,
          [pinnedEventIds],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setPinnedEvents,
            [pinnedEventIds],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setPinnedEvents,
            [pinnedEventIds],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String? getMention(String? mention) => (super.noSuchMethod(
        Invocation.method(
          #getMention,
          [mention],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  _i5.Future<String?> sendTextEvent(
    String? message, {
    String? txid,
    _i2.Event? inReplyTo,
    String? editEventId,
    bool? parseMarkdown = true,
    bool? parseCommands = true,
    String? msgtype = 'm.text',
    String? threadRootEventId,
    String? threadLastEventId,
    StringBuffer? commandStdout,
    bool? addMentions = true,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendTextEvent,
          [message],
          {
            #txid: txid,
            #inReplyTo: inReplyTo,
            #editEventId: editEventId,
            #parseMarkdown: parseMarkdown,
            #parseCommands: parseCommands,
            #msgtype: msgtype,
            #threadRootEventId: threadRootEventId,
            #threadLastEventId: threadLastEventId,
            #commandStdout: commandStdout,
            #addMentions: addMentions,
            #displayPendingEvent: displayPendingEvent,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> sendReaction(
    String? eventId,
    String? key, {
    String? txid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReaction,
          [
            eventId,
            key,
          ],
          {#txid: txid},
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> sendLocation(
    String? body,
    String? geoUri, {
    String? txid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendLocation,
          [
            body,
            geoUri,
          ],
          {#txid: txid},
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> sendFileEvent(
    _i2.MatrixFile? file, {
    String? txid,
    _i2.Event? inReplyTo,
    String? editEventId,
    int? shrinkImageMaxDimension,
    _i2.MatrixImageFile? thumbnail,
    Map<String, dynamic>? extraContent,
    String? threadRootEventId,
    String? threadLastEventId,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFileEvent,
          [file],
          {
            #txid: txid,
            #inReplyTo: inReplyTo,
            #editEventId: editEventId,
            #shrinkImageMaxDimension: shrinkImageMaxDimension,
            #thumbnail: thumbnail,
            #extraContent: extraContent,
            #threadRootEventId: threadRootEventId,
            #threadLastEventId: threadLastEventId,
            #displayPendingEvent: displayPendingEvent,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i2.EncryptionHealthState> calcEncryptionHealthState() =>
      (super.noSuchMethod(
        Invocation.method(
          #calcEncryptionHealthState,
          [],
        ),
        returnValue: _i5.Future<_i2.EncryptionHealthState>.value(
            _i2.EncryptionHealthState.allVerified),
        returnValueForMissingStub: _i5.Future<_i2.EncryptionHealthState>.value(
            _i2.EncryptionHealthState.allVerified),
      ) as _i5.Future<_i2.EncryptionHealthState>);

  @override
  _i5.Future<String?> sendEvent(
    Map<String, dynamic>? content, {
    String? type = 'm.room.message',
    String? txid,
    _i2.Event? inReplyTo,
    String? editEventId,
    String? threadRootEventId,
    String? threadLastEventId,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEvent,
          [content],
          {
            #type: type,
            #txid: txid,
            #inReplyTo: inReplyTo,
            #editEventId: editEventId,
            #threadRootEventId: threadRootEventId,
            #threadLastEventId: threadLastEventId,
            #displayPendingEvent: displayPendingEvent,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> join({bool? leaveIfNotFound = true}) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [],
          {#leaveIfNotFound: leaveIfNotFound},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> leave() => (super.noSuchMethod(
        Invocation.method(
          #leave,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forget() => (super.noSuchMethod(
        Invocation.method(
          #forget,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> kick(String? userID) => (super.noSuchMethod(
        Invocation.method(
          #kick,
          [userID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> ban(String? userID) => (super.noSuchMethod(
        Invocation.method(
          #ban,
          [userID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unban(String? userID) => (super.noSuchMethod(
        Invocation.method(
          #unban,
          [userID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> setPower(
    String? userId,
    int? power,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPower,
          [
            userId,
            power,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setPower,
            [
              userId,
              power,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setPower,
            [
              userId,
              power,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> invite(
    String? userID, {
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #invite,
          [userID],
          {#reason: reason},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> requestHistory({
    int? historyCount = 30,
    void Function()? onHistoryReceived,
    dynamic direction = _i2.Direction.b,
    _i2.StateFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestHistory,
          [],
          {
            #historyCount: historyCount,
            #onHistoryReceived: onHistoryReceived,
            #direction: direction,
            #filter: filter,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> addToDirectChat(String? userID) => (super.noSuchMethod(
        Invocation.method(
          #addToDirectChat,
          [userID],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromDirectChat() => (super.noSuchMethod(
        Invocation.method(
          #removeFromDirectChat,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setReadMarker(
    String? eventId, {
    String? mRead,
    bool? public,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReadMarker,
          [eventId],
          {
            #mRead: mRead,
            #public: public,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.TimelineChunk?> getEventContext(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventContext,
          [eventId],
        ),
        returnValue: _i5.Future<_i7.TimelineChunk?>.value(),
        returnValueForMissingStub: _i5.Future<_i7.TimelineChunk?>.value(),
      ) as _i5.Future<_i7.TimelineChunk?>);

  @override
  _i5.Future<void> postReceipt(
    String? eventId, {
    _i2.ReceiptType? type = _i2.ReceiptType.mRead,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postReceipt,
          [eventId],
          {#type: type},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Timeline> getTimeline({
    void Function(int)? onChange,
    void Function(int)? onRemove,
    void Function(int)? onInsert,
    void Function()? onNewEvent,
    void Function()? onUpdate,
    String? eventContextId,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTimeline,
          [],
          {
            #onChange: onChange,
            #onRemove: onRemove,
            #onInsert: onInsert,
            #onNewEvent: onNewEvent,
            #onUpdate: onUpdate,
            #eventContextId: eventContextId,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<_i2.Timeline>.value(_FakeTimeline_6(
          this,
          Invocation.method(
            #getTimeline,
            [],
            {
              #onChange: onChange,
              #onRemove: onRemove,
              #onInsert: onInsert,
              #onNewEvent: onNewEvent,
              #onUpdate: onUpdate,
              #eventContextId: eventContextId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Timeline>.value(_FakeTimeline_6(
          this,
          Invocation.method(
            #getTimeline,
            [],
            {
              #onChange: onChange,
              #onRemove: onRemove,
              #onInsert: onInsert,
              #onNewEvent: onNewEvent,
              #onUpdate: onUpdate,
              #eventContextId: eventContextId,
              #limit: limit,
            },
          ),
        )),
      ) as _i5.Future<_i2.Timeline>);

  @override
  List<_i2.User> getParticipants(
          [List<_i2.Membership>? membershipFilter = const [
            _i2.Membership.join,
            _i2.Membership.invite,
            _i2.Membership.knock,
          ]]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipants,
          [membershipFilter],
        ),
        returnValue: <_i2.User>[],
        returnValueForMissingStub: <_i2.User>[],
      ) as List<_i2.User>);

  @override
  _i5.Future<List<_i2.User>> requestParticipants([
    List<_i2.Membership>? membershipFilter = const [
      _i2.Membership.join,
      _i2.Membership.invite,
      _i2.Membership.knock,
    ],
    bool? suppressWarning = false,
    bool? cache,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestParticipants,
          [
            membershipFilter,
            suppressWarning,
            cache,
          ],
        ),
        returnValue: _i5.Future<List<_i2.User>>.value(<_i2.User>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i5.Future<List<_i2.User>>);

  @override
  _i2.User getUserByMXIDSync(String? mxID) => (super.noSuchMethod(
        Invocation.method(
          #getUserByMXIDSync,
          [mxID],
        ),
        returnValue: _FakeUser_7(
          this,
          Invocation.method(
            #getUserByMXIDSync,
            [mxID],
          ),
        ),
        returnValueForMissingStub: _FakeUser_7(
          this,
          Invocation.method(
            #getUserByMXIDSync,
            [mxID],
          ),
        ),
      ) as _i2.User);

  @override
  _i2.User unsafeGetUserFromMemoryOrFallback(String? mxID) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsafeGetUserFromMemoryOrFallback,
          [mxID],
        ),
        returnValue: _FakeUser_7(
          this,
          Invocation.method(
            #unsafeGetUserFromMemoryOrFallback,
            [mxID],
          ),
        ),
        returnValueForMissingStub: _FakeUser_7(
          this,
          Invocation.method(
            #unsafeGetUserFromMemoryOrFallback,
            [mxID],
          ),
        ),
      ) as _i2.User);

  @override
  _i5.Future<_i2.User?> requestUser(
    String? mxID, {
    bool? ignoreErrors = false,
    bool? requestState = true,
    bool? requestProfile = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUser,
          [mxID],
          {
            #ignoreErrors: ignoreErrors,
            #requestState: requestState,
            #requestProfile: requestProfile,
          },
        ),
        returnValue: _i5.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.User?>.value(),
      ) as _i5.Future<_i2.User?>);

  @override
  _i5.Future<_i2.Event?> getEventById(String? eventID) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventID],
        ),
        returnValue: _i5.Future<_i2.Event?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Event?>.value(),
      ) as _i5.Future<_i2.Event?>);

  @override
  int getPowerLevelByUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getPowerLevelByUserId,
          [userId],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<String> setAvatar(_i2.MatrixFile? file) => (super.noSuchMethod(
        Invocation.method(
          #setAvatar,
          [file],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setAvatar,
            [file],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #setAvatar,
            [file],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  bool canChangeStateEvent(String? action) => (super.noSuchMethod(
        Invocation.method(
          #canChangeStateEvent,
          [action],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int powerForChangingStateEvent(String? action) => (super.noSuchMethod(
        Invocation.method(
          #powerForChangingStateEvent,
          [action],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i5.Future<void> enableGroupCalls() => (super.noSuchMethod(
        Invocation.method(
          #enableGroupCalls,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  int getDefaultPowerLevel(Map<String, dynamic>? powerLevelMap) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultPowerLevel,
          [powerLevelMap],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool canSendEvent(String? eventType) => (super.noSuchMethod(
        Invocation.method(
          #canSendEvent,
          [eventType],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool canSendNotification(
    String? userid, {
    String? notificationType = 'room',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canSendNotification,
          [userid],
          {#notificationType: notificationType},
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> setPushRuleState(_i2.PushRuleState? newState) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPushRuleState,
          [newState],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> redactEvent(
    String? eventId, {
    String? reason,
    String? txid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redactEvent,
          [eventId],
          {
            #reason: reason,
            #txid: txid,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> setTyping(
    bool? isTyping, {
    int? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTyping,
          [isTyping],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setJoinRules(
    _i2.JoinRules? joinRules, {
    List<String>? allowConditionRoomIds,
    String? allowConditionRoomId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setJoinRules,
          [joinRules],
          {
            #allowConditionRoomIds: allowConditionRoomIds,
            #allowConditionRoomId: allowConditionRoomId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setGuestAccess(_i2.GuestAccess? guestAccess) =>
      (super.noSuchMethod(
        Invocation.method(
          #setGuestAccess,
          [guestAccess],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setHistoryVisibility(
          _i2.HistoryVisibility? historyVisibility) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHistoryVisibility,
          [historyVisibility],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enableEncryption({int? algorithmIndex = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableEncryption,
          [],
          {#algorithmIndex: algorithmIndex},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.DeviceKeys>> getUserDeviceKeys() => (super.noSuchMethod(
        Invocation.method(
          #getUserDeviceKeys,
          [],
        ),
        returnValue: _i5.Future<List<_i2.DeviceKeys>>.value(<_i2.DeviceKeys>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i2.DeviceKeys>>.value(<_i2.DeviceKeys>[]),
      ) as _i5.Future<List<_i2.DeviceKeys>>);

  @override
  _i5.Future<void> requestSessionKey(
    String? sessionId,
    String? senderKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestSessionKey,
          [
            sessionId,
            senderKey,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSpaceChild(
    String? roomId, {
    List<String>? via,
    String? order,
    bool? suggested,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSpaceChild,
          [roomId],
          {
            #via: via,
            #order: order,
            #suggested: suggested,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Uri> matrixToInviteLink() => (super.noSuchMethod(
        Invocation.method(
          #matrixToInviteLink,
          [],
        ),
        returnValue: _i5.Future<Uri>.value(_FakeUri_8(
          this,
          Invocation.method(
            #matrixToInviteLink,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<Uri>.value(_FakeUri_8(
          this,
          Invocation.method(
            #matrixToInviteLink,
            [],
          ),
        )),
      ) as _i5.Future<Uri>);

  @override
  _i5.Future<void> removeSpaceChild(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #removeSpaceChild,
          [roomId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<
      ({
        List<_i2.Event> events,
        String? nextBatch,
        DateTime? searchedUntil
      })> searchEvents({
    String? searchTerm,
    bool Function(_i2.Event)? searchFunc,
    String? nextBatch,
    int? limit = 1000,
    Set<String>? includeEventTypes = const {
      'm.room.message',
      'm.room.encrypted',
    },
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEvents,
          [],
          {
            #searchTerm: searchTerm,
            #searchFunc: searchFunc,
            #nextBatch: nextBatch,
            #limit: limit,
            #includeEventTypes: includeEventTypes,
          },
        ),
        returnValue: _i5.Future<
                ({
                  List<_i2.Event> events,
                  String? nextBatch,
                  DateTime? searchedUntil
                })>.value(
            (events: <_i2.Event>[], nextBatch: null, searchedUntil: null)),
        returnValueForMissingStub: _i5.Future<
                ({
                  List<_i2.Event> events,
                  String? nextBatch,
                  DateTime? searchedUntil
                })>.value(
            (events: <_i2.Event>[], nextBatch: null, searchedUntil: null)),
      ) as _i5.Future<
          ({
            List<_i2.Event> events,
            String? nextBatch,
            DateTime? searchedUntil
          })>);
}

/// A class which mocks [Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvent extends _i1.Mock implements _i2.Event {
  @override
  _i2.User get sender => (super.noSuchMethod(
        Invocation.getter(#sender),
        returnValue: _FakeUser_7(
          this,
          Invocation.getter(#sender),
        ),
        returnValueForMissingStub: _FakeUser_7(
          this,
          Invocation.getter(#sender),
        ),
      ) as _i2.User);

  @override
  _i2.User get senderFromMemoryOrFallback => (super.noSuchMethod(
        Invocation.getter(#senderFromMemoryOrFallback),
        returnValue: _FakeUser_7(
          this,
          Invocation.getter(#senderFromMemoryOrFallback),
        ),
        returnValueForMissingStub: _FakeUser_7(
          this,
          Invocation.getter(#senderFromMemoryOrFallback),
        ),
      ) as _i2.User);

  @override
  _i2.Room get room => (super.noSuchMethod(
        Invocation.getter(#room),
        returnValue: _FakeRoom_9(
          this,
          Invocation.getter(#room),
        ),
        returnValueForMissingStub: _FakeRoom_9(
          this,
          Invocation.getter(#room),
        ),
      ) as _i2.Room);

  @override
  _i2.EventStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i2.EventStatus.error,
        returnValueForMissingStub: _i2.EventStatus.error,
      ) as _i2.EventStatus);

  @override
  bool get redacted => (super.noSuchMethod(
        Invocation.getter(#redacted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.User get asUser => (super.noSuchMethod(
        Invocation.getter(#asUser),
        returnValue: _FakeUser_7(
          this,
          Invocation.getter(#asUser),
        ),
        returnValueForMissingStub: _FakeUser_7(
          this,
          Invocation.getter(#asUser),
        ),
      ) as _i2.User);

  @override
  String get messageType => (super.noSuchMethod(
        Invocation.getter(#messageType),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#messageType),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#messageType),
        ),
      ) as String);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);

  @override
  String get formattedText => (super.noSuchMethod(
        Invocation.getter(#formattedText),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#formattedText),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#formattedText),
        ),
      ) as String);

  @override
  String get body => (super.noSuchMethod(
        Invocation.getter(#body),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
      ) as String);

  @override
  String get plaintextBody => (super.noSuchMethod(
        Invocation.getter(#plaintextBody),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#plaintextBody),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#plaintextBody),
        ),
      ) as String);

  @override
  List<_i2.Receipt> get receipts => (super.noSuchMethod(
        Invocation.getter(#receipts),
        returnValue: <_i2.Receipt>[],
        returnValueForMissingStub: <_i2.Receipt>[],
      ) as List<_i2.Receipt>);

  @override
  bool get canRedact => (super.noSuchMethod(
        Invocation.getter(#canRedact),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, Object?> get infoMap => (super.noSuchMethod(
        Invocation.getter(#infoMap),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  Map<String, Object?> get thumbnailInfoMap => (super.noSuchMethod(
        Invocation.getter(#thumbnailInfoMap),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  bool get hasAttachment => (super.noSuchMethod(
        Invocation.getter(#hasAttachment),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasThumbnail => (super.noSuchMethod(
        Invocation.getter(#hasThumbnail),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAttachmentEncrypted => (super.noSuchMethod(
        Invocation.getter(#isAttachmentEncrypted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isThumbnailEncrypted => (super.noSuchMethod(
        Invocation.getter(#isThumbnailEncrypted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get attachmentMimetype => (super.noSuchMethod(
        Invocation.getter(#attachmentMimetype),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#attachmentMimetype),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#attachmentMimetype),
        ),
      ) as String);

  @override
  String get thumbnailMimetype => (super.noSuchMethod(
        Invocation.getter(#thumbnailMimetype),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#thumbnailMimetype),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#thumbnailMimetype),
        ),
      ) as String);

  @override
  bool get isEventTypeKnown => (super.noSuchMethod(
        Invocation.getter(#isEventTypeKnown),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRichMessage => (super.noSuchMethod(
        Invocation.getter(#isRichMessage),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get onlyEmotes => (super.noSuchMethod(
        Invocation.getter(#onlyEmotes),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get numberEmotes => (super.noSuchMethod(
        Invocation.getter(#numberEmotes),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  ({bool room, List<String> userIds}) get mentions => (super.noSuchMethod(
        Invocation.getter(#mentions),
        returnValue: (room: false, userIds: <String>[]),
        returnValueForMissingStub: (room: false, userIds: <String>[]),
      ) as ({bool room, List<String> userIds}));

  @override
  set status(_i2.EventStatus? value) => super.noSuchMethod(
        Invocation.setter(
          #status,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get eventId => (super.noSuchMethod(
        Invocation.getter(#eventId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#eventId),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#eventId),
        ),
      ) as String);

  @override
  DateTime get originServerTs => (super.noSuchMethod(
        Invocation.getter(#originServerTs),
        returnValue: _FakeDateTime_3(
          this,
          Invocation.getter(#originServerTs),
        ),
        returnValueForMissingStub: _FakeDateTime_3(
          this,
          Invocation.getter(#originServerTs),
        ),
      ) as DateTime);

  @override
  set eventId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #eventId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set roomId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #roomId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set originServerTs(DateTime? value) => super.noSuchMethod(
        Invocation.setter(
          #originServerTs,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unsigned(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #unsigned,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set prevContent(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #prevContent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set redacts(String? value) => super.noSuchMethod(
        Invocation.setter(
          #redacts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stateKey(String? value) => super.noSuchMethod(
        Invocation.setter(
          #stateKey,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get senderId => (super.noSuchMethod(
        Invocation.getter(#senderId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#senderId),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#senderId),
        ),
      ) as String);

  @override
  set senderId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #senderId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  Map<String, Object?> get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  set type(String? value) => super.noSuchMethod(
        Invocation.setter(
          #type,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set content(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #content,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i2.User?> fetchSenderUser() => (super.noSuchMethod(
        Invocation.method(
          #fetchSenderUser,
          [],
        ),
        returnValue: _i5.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.User?>.value(),
      ) as _i5.Future<_i2.User?>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void setRedactionEvent(_i2.Event? redactedBecause) => super.noSuchMethod(
        Invocation.method(
          #setRedactionEvent,
          [redactedBecause],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> cancelSend() => (super.noSuchMethod(
        Invocation.method(
          #cancelSend,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> sendAgain({String? txid}) => (super.noSuchMethod(
        Invocation.method(
          #sendAgain,
          [],
          {#txid: txid},
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> redactEvent({
    String? reason,
    String? txid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redactEvent,
          [],
          {
            #reason: reason,
            #txid: txid,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i2.Event?> getReplyEvent(_i2.Timeline? timeline) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReplyEvent,
          [timeline],
        ),
        returnValue: _i5.Future<_i2.Event?>.value(),
        returnValueForMissingStub: _i5.Future<_i2.Event?>.value(),
      ) as _i5.Future<_i2.Event?>);

  @override
  _i5.Future<void> requestKey() => (super.noSuchMethod(
        Invocation.method(
          #requestKey,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Uri? attachmentOrThumbnailMxcUrl({bool? getThumbnail = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #attachmentOrThumbnailMxcUrl,
          [],
          {#getThumbnail: getThumbnail},
        ),
        returnValueForMissingStub: null,
      ) as Uri?);

  @override
  _i5.Future<Uri?> getAttachmentUri({
    bool? getThumbnail = false,
    bool? useThumbnailMxcUrl = false,
    double? width = 800.0,
    double? height = 800.0,
    _i2.ThumbnailMethod? method = _i2.ThumbnailMethod.scale,
    int? minNoThumbSize = 81920,
    bool? animated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachmentUri,
          [],
          {
            #getThumbnail: getThumbnail,
            #useThumbnailMxcUrl: useThumbnailMxcUrl,
            #width: width,
            #height: height,
            #method: method,
            #minNoThumbSize: minNoThumbSize,
            #animated: animated,
          },
        ),
        returnValue: _i5.Future<Uri?>.value(),
        returnValueForMissingStub: _i5.Future<Uri?>.value(),
      ) as _i5.Future<Uri?>);

  @override
  Uri? getAttachmentUrl({
    bool? getThumbnail = false,
    bool? useThumbnailMxcUrl = false,
    double? width = 800.0,
    double? height = 800.0,
    _i2.ThumbnailMethod? method = _i2.ThumbnailMethod.scale,
    int? minNoThumbSize = 81920,
    bool? animated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachmentUrl,
          [],
          {
            #getThumbnail: getThumbnail,
            #useThumbnailMxcUrl: useThumbnailMxcUrl,
            #width: width,
            #height: height,
            #method: method,
            #minNoThumbSize: minNoThumbSize,
            #animated: animated,
          },
        ),
        returnValueForMissingStub: null,
      ) as Uri?);

  @override
  _i5.Future<bool> isAttachmentInLocalStore({bool? getThumbnail = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAttachmentInLocalStore,
          [],
          {#getThumbnail: getThumbnail},
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.MatrixFile> downloadAndDecryptAttachment({
    bool? getThumbnail = false,
    _i5.Future<_i8.Uint8List> Function(Uri)? downloadCallback,
    bool? fromLocalStoreOnly = false,
    void Function(int)? onDownloadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAndDecryptAttachment,
          [],
          {
            #getThumbnail: getThumbnail,
            #downloadCallback: downloadCallback,
            #fromLocalStoreOnly: fromLocalStoreOnly,
            #onDownloadProgress: onDownloadProgress,
          },
        ),
        returnValue: _i5.Future<_i2.MatrixFile>.value(_FakeMatrixFile_10(
          this,
          Invocation.method(
            #downloadAndDecryptAttachment,
            [],
            {
              #getThumbnail: getThumbnail,
              #downloadCallback: downloadCallback,
              #fromLocalStoreOnly: fromLocalStoreOnly,
              #onDownloadProgress: onDownloadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.MatrixFile>.value(_FakeMatrixFile_10(
          this,
          Invocation.method(
            #downloadAndDecryptAttachment,
            [],
            {
              #getThumbnail: getThumbnail,
              #downloadCallback: downloadCallback,
              #fromLocalStoreOnly: fromLocalStoreOnly,
              #onDownloadProgress: onDownloadProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.MatrixFile>);

  @override
  _i5.Future<String> calcLocalizedBody(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcLocalizedBody,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String getLocalizedBody(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizedBody,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  String calcLocalizedBodyFallback(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcLocalizedBodyFallback,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBodyFallback,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBodyFallback,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  String calcUnlocalizedBody({
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcUnlocalizedBody,
          [],
          {
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcUnlocalizedBody,
            [],
            {
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #calcUnlocalizedBody,
            [],
            {
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  bool matchesEventOrTransactionId(String? search) => (super.noSuchMethod(
        Invocation.method(
          #matchesEventOrTransactionId,
          [search],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String? inReplyToEventId({bool? includingFallback = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #inReplyToEventId,
          [],
          {#includingFallback: includingFallback},
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool hasAggregatedEvents(
    _i2.Timeline? timeline,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAggregatedEvents,
          [
            timeline,
            type,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Set<_i2.Event> aggregatedEvents(
    _i2.Timeline? timeline,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregatedEvents,
          [
            timeline,
            type,
          ],
        ),
        returnValue: <_i2.Event>{},
        returnValueForMissingStub: <_i2.Event>{},
      ) as Set<_i2.Event>);

  @override
  _i2.Event getDisplayEvent(_i2.Timeline? timeline) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayEvent,
          [timeline],
        ),
        returnValue: _FakeEvent_11(
          this,
          Invocation.method(
            #getDisplayEvent,
            [timeline],
          ),
        ),
        returnValueForMissingStub: _FakeEvent_11(
          this,
          Invocation.method(
            #getDisplayEvent,
            [timeline],
          ),
        ),
      ) as _i2.Event);
}
