// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/widgets/chat/audio_bubble_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i8;

import 'package:kohera/features/chat/services/media_playback_service.dart'
    as _i6;
import 'package:matrix/matrix.dart' as _i2;
import 'package:media_kit/media_kit.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoom_1 extends _i1.SmartFake implements _i2.Room {
  _FakeRoom_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatrixFile_3 extends _i1.SmartFake implements _i2.MatrixFile {
  _FakeMatrixFile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_4 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvent extends _i1.Mock implements _i2.Event {
  @override
  _i2.User get sender => (super.noSuchMethod(
        Invocation.getter(#sender),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#sender),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.getter(#sender),
        ),
      ) as _i2.User);

  @override
  _i2.User get senderFromMemoryOrFallback => (super.noSuchMethod(
        Invocation.getter(#senderFromMemoryOrFallback),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#senderFromMemoryOrFallback),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.getter(#senderFromMemoryOrFallback),
        ),
      ) as _i2.User);

  @override
  _i2.Room get room => (super.noSuchMethod(
        Invocation.getter(#room),
        returnValue: _FakeRoom_1(
          this,
          Invocation.getter(#room),
        ),
        returnValueForMissingStub: _FakeRoom_1(
          this,
          Invocation.getter(#room),
        ),
      ) as _i2.Room);

  @override
  _i2.EventStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i2.EventStatus.error,
        returnValueForMissingStub: _i2.EventStatus.error,
      ) as _i2.EventStatus);

  @override
  bool get redacted => (super.noSuchMethod(
        Invocation.getter(#redacted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.User get asUser => (super.noSuchMethod(
        Invocation.getter(#asUser),
        returnValue: _FakeUser_0(
          this,
          Invocation.getter(#asUser),
        ),
        returnValueForMissingStub: _FakeUser_0(
          this,
          Invocation.getter(#asUser),
        ),
      ) as _i2.User);

  @override
  String get messageType => (super.noSuchMethod(
        Invocation.getter(#messageType),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#messageType),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#messageType),
        ),
      ) as String);

  @override
  String get text => (super.noSuchMethod(
        Invocation.getter(#text),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#text),
        ),
      ) as String);

  @override
  String get formattedText => (super.noSuchMethod(
        Invocation.getter(#formattedText),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#formattedText),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#formattedText),
        ),
      ) as String);

  @override
  String get body => (super.noSuchMethod(
        Invocation.getter(#body),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
      ) as String);

  @override
  String get plaintextBody => (super.noSuchMethod(
        Invocation.getter(#plaintextBody),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#plaintextBody),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#plaintextBody),
        ),
      ) as String);

  @override
  List<_i2.Receipt> get receipts => (super.noSuchMethod(
        Invocation.getter(#receipts),
        returnValue: <_i2.Receipt>[],
        returnValueForMissingStub: <_i2.Receipt>[],
      ) as List<_i2.Receipt>);

  @override
  bool get canRedact => (super.noSuchMethod(
        Invocation.getter(#canRedact),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, Object?> get infoMap => (super.noSuchMethod(
        Invocation.getter(#infoMap),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  Map<String, Object?> get thumbnailInfoMap => (super.noSuchMethod(
        Invocation.getter(#thumbnailInfoMap),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  bool get hasAttachment => (super.noSuchMethod(
        Invocation.getter(#hasAttachment),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasThumbnail => (super.noSuchMethod(
        Invocation.getter(#hasThumbnail),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAttachmentEncrypted => (super.noSuchMethod(
        Invocation.getter(#isAttachmentEncrypted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isThumbnailEncrypted => (super.noSuchMethod(
        Invocation.getter(#isThumbnailEncrypted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get attachmentMimetype => (super.noSuchMethod(
        Invocation.getter(#attachmentMimetype),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#attachmentMimetype),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#attachmentMimetype),
        ),
      ) as String);

  @override
  String get thumbnailMimetype => (super.noSuchMethod(
        Invocation.getter(#thumbnailMimetype),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#thumbnailMimetype),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#thumbnailMimetype),
        ),
      ) as String);

  @override
  bool get isEventTypeKnown => (super.noSuchMethod(
        Invocation.getter(#isEventTypeKnown),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isRichMessage => (super.noSuchMethod(
        Invocation.getter(#isRichMessage),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get onlyEmotes => (super.noSuchMethod(
        Invocation.getter(#onlyEmotes),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get numberEmotes => (super.noSuchMethod(
        Invocation.getter(#numberEmotes),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  ({bool room, List<String> userIds}) get mentions => (super.noSuchMethod(
        Invocation.getter(#mentions),
        returnValue: (room: false, userIds: <String>[]),
        returnValueForMissingStub: (room: false, userIds: <String>[]),
      ) as ({bool room, List<String> userIds}));

  @override
  set status(_i2.EventStatus? value) => super.noSuchMethod(
        Invocation.setter(
          #status,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get eventId => (super.noSuchMethod(
        Invocation.getter(#eventId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#eventId),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#eventId),
        ),
      ) as String);

  @override
  DateTime get originServerTs => (super.noSuchMethod(
        Invocation.getter(#originServerTs),
        returnValue: _FakeDateTime_2(
          this,
          Invocation.getter(#originServerTs),
        ),
        returnValueForMissingStub: _FakeDateTime_2(
          this,
          Invocation.getter(#originServerTs),
        ),
      ) as DateTime);

  @override
  set eventId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #eventId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set roomId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #roomId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set originServerTs(DateTime? value) => super.noSuchMethod(
        Invocation.setter(
          #originServerTs,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set unsigned(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #unsigned,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set prevContent(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #prevContent,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set redacts(String? value) => super.noSuchMethod(
        Invocation.setter(
          #redacts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stateKey(String? value) => super.noSuchMethod(
        Invocation.setter(
          #stateKey,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get senderId => (super.noSuchMethod(
        Invocation.getter(#senderId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#senderId),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#senderId),
        ),
      ) as String);

  @override
  set senderId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #senderId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#type),
        ),
      ) as String);

  @override
  Map<String, Object?> get content => (super.noSuchMethod(
        Invocation.getter(#content),
        returnValue: <String, Object?>{},
        returnValueForMissingStub: <String, Object?>{},
      ) as Map<String, Object?>);

  @override
  set type(String? value) => super.noSuchMethod(
        Invocation.setter(
          #type,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set content(Map<String, Object?>? value) => super.noSuchMethod(
        Invocation.setter(
          #content,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i2.User?> fetchSenderUser() => (super.noSuchMethod(
        Invocation.method(
          #fetchSenderUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void setRedactionEvent(_i2.Event? redactedBecause) => super.noSuchMethod(
        Invocation.method(
          #setRedactionEvent,
          [redactedBecause],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> cancelSend() => (super.noSuchMethod(
        Invocation.method(
          #cancelSend,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> sendAgain({String? txid}) => (super.noSuchMethod(
        Invocation.method(
          #sendAgain,
          [],
          {#txid: txid},
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> redactEvent({
    String? reason,
    String? txid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redactEvent,
          [],
          {
            #reason: reason,
            #txid: txid,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i2.Event?> getReplyEvent(_i2.Timeline? timeline) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReplyEvent,
          [timeline],
        ),
        returnValue: _i4.Future<_i2.Event?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Event?>.value(),
      ) as _i4.Future<_i2.Event?>);

  @override
  _i4.Future<void> requestKey() => (super.noSuchMethod(
        Invocation.method(
          #requestKey,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Uri? attachmentOrThumbnailMxcUrl({bool? getThumbnail = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #attachmentOrThumbnailMxcUrl,
          [],
          {#getThumbnail: getThumbnail},
        ),
        returnValueForMissingStub: null,
      ) as Uri?);

  @override
  _i4.Future<Uri?> getAttachmentUri({
    bool? getThumbnail = false,
    bool? useThumbnailMxcUrl = false,
    double? width = 800.0,
    double? height = 800.0,
    _i2.ThumbnailMethod? method = _i2.ThumbnailMethod.scale,
    int? minNoThumbSize = 81920,
    bool? animated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachmentUri,
          [],
          {
            #getThumbnail: getThumbnail,
            #useThumbnailMxcUrl: useThumbnailMxcUrl,
            #width: width,
            #height: height,
            #method: method,
            #minNoThumbSize: minNoThumbSize,
            #animated: animated,
          },
        ),
        returnValue: _i4.Future<Uri?>.value(),
        returnValueForMissingStub: _i4.Future<Uri?>.value(),
      ) as _i4.Future<Uri?>);

  @override
  Uri? getAttachmentUrl({
    bool? getThumbnail = false,
    bool? useThumbnailMxcUrl = false,
    double? width = 800.0,
    double? height = 800.0,
    _i2.ThumbnailMethod? method = _i2.ThumbnailMethod.scale,
    int? minNoThumbSize = 81920,
    bool? animated = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttachmentUrl,
          [],
          {
            #getThumbnail: getThumbnail,
            #useThumbnailMxcUrl: useThumbnailMxcUrl,
            #width: width,
            #height: height,
            #method: method,
            #minNoThumbSize: minNoThumbSize,
            #animated: animated,
          },
        ),
        returnValueForMissingStub: null,
      ) as Uri?);

  @override
  _i4.Future<bool> isAttachmentInLocalStore({bool? getThumbnail = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isAttachmentInLocalStore,
          [],
          {#getThumbnail: getThumbnail},
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.MatrixFile> downloadAndDecryptAttachment({
    bool? getThumbnail = false,
    _i4.Future<_i5.Uint8List> Function(Uri)? downloadCallback,
    bool? fromLocalStoreOnly = false,
    void Function(int)? onDownloadProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAndDecryptAttachment,
          [],
          {
            #getThumbnail: getThumbnail,
            #downloadCallback: downloadCallback,
            #fromLocalStoreOnly: fromLocalStoreOnly,
            #onDownloadProgress: onDownloadProgress,
          },
        ),
        returnValue: _i4.Future<_i2.MatrixFile>.value(_FakeMatrixFile_3(
          this,
          Invocation.method(
            #downloadAndDecryptAttachment,
            [],
            {
              #getThumbnail: getThumbnail,
              #downloadCallback: downloadCallback,
              #fromLocalStoreOnly: fromLocalStoreOnly,
              #onDownloadProgress: onDownloadProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MatrixFile>.value(_FakeMatrixFile_3(
          this,
          Invocation.method(
            #downloadAndDecryptAttachment,
            [],
            {
              #getThumbnail: getThumbnail,
              #downloadCallback: downloadCallback,
              #fromLocalStoreOnly: fromLocalStoreOnly,
              #onDownloadProgress: onDownloadProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.MatrixFile>);

  @override
  _i4.Future<String> calcLocalizedBody(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcLocalizedBody,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  String getLocalizedBody(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalizedBody,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getLocalizedBody,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  String calcLocalizedBodyFallback(
    _i2.MatrixLocalizations? i18n, {
    bool? withSenderNamePrefix = false,
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcLocalizedBodyFallback,
          [i18n],
          {
            #withSenderNamePrefix: withSenderNamePrefix,
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBodyFallback,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcLocalizedBodyFallback,
            [i18n],
            {
              #withSenderNamePrefix: withSenderNamePrefix,
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  String calcUnlocalizedBody({
    bool? hideReply = false,
    bool? hideEdit = false,
    bool? plaintextBody = false,
    bool? removeMarkdown = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calcUnlocalizedBody,
          [],
          {
            #hideReply: hideReply,
            #hideEdit: hideEdit,
            #plaintextBody: plaintextBody,
            #removeMarkdown: removeMarkdown,
          },
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcUnlocalizedBody,
            [],
            {
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #calcUnlocalizedBody,
            [],
            {
              #hideReply: hideReply,
              #hideEdit: hideEdit,
              #plaintextBody: plaintextBody,
              #removeMarkdown: removeMarkdown,
            },
          ),
        ),
      ) as String);

  @override
  bool matchesEventOrTransactionId(String? search) => (super.noSuchMethod(
        Invocation.method(
          #matchesEventOrTransactionId,
          [search],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String? inReplyToEventId({bool? includingFallback = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #inReplyToEventId,
          [],
          {#includingFallback: includingFallback},
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool hasAggregatedEvents(
    _i2.Timeline? timeline,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAggregatedEvents,
          [
            timeline,
            type,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Set<_i2.Event> aggregatedEvents(
    _i2.Timeline? timeline,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregatedEvents,
          [
            timeline,
            type,
          ],
        ),
        returnValue: <_i2.Event>{},
        returnValueForMissingStub: <_i2.Event>{},
      ) as Set<_i2.Event>);

  @override
  _i2.Event getDisplayEvent(_i2.Timeline? timeline) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayEvent,
          [timeline],
        ),
        returnValue: _FakeEvent_4(
          this,
          Invocation.method(
            #getDisplayEvent,
            [timeline],
          ),
        ),
        returnValueForMissingStub: _FakeEvent_4(
          this,
          Invocation.method(
            #getDisplayEvent,
            [timeline],
          ),
        ),
      ) as _i2.Event);
}

/// A class which mocks [MediaPlaybackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaPlaybackService extends _i1.Mock
    implements _i6.MediaPlaybackService {
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void registerPlayer(
    String? eventId,
    _i7.Player? player,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #registerPlayer,
          [
            eventId,
            player,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterPlayer(String? eventId) => super.noSuchMethod(
        Invocation.method(
          #unregisterPlayer,
          [eventId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseActive() => super.noSuchMethod(
        Invocation.method(
          #pauseActive,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
