// Mocks generated by Mockito 5.4.6 from annotations
// in lattice/test/widgets/chat/link_preview_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:lattice/features/chat/services/opengraph_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OpenGraphService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenGraphService extends _i1.Mock implements _i2.OpenGraphService {
  @override
  set dnsResolver(
          _i3.Future<List<_i4.InternetAddress>> Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #dnsResolver,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i2.OpenGraphData?> fetch(String? url) => (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [url],
        ),
        returnValue: _i3.Future<_i2.OpenGraphData?>.value(),
        returnValueForMissingStub: _i3.Future<_i2.OpenGraphData?>.value(),
      ) as _i3.Future<_i2.OpenGraphData?>);

  @override
  _i2.OpenGraphData? parse(
    String? html,
    String? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parse,
          [
            html,
            url,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i2.OpenGraphData?);
}
